language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    - CODECOV_TOKEN=2072cbf1-2dcf-4982-b698-178d4b4047e4

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    bash <(curl -s https://codecov.io/bash)
  fi
